### ISSUE TITLE
The sample plugin doesn't tree shake this library.

### ISSUE THREAD

**Issue by phibr0** [obsidian-community/obsidian-community-lib#14]
If one compiles their Plugin with this Library, using the esbuild (or old rollup config) from the sample Plugin, all provided methods are included, even the ones that aren't used. 
I am not sure if this is an Issue of this Library or the sample Plugin configuration, and while the Library is pretty small it's also not that big of a deal, but it might become one in the Future.

**Comment by SkepticMystic** [comment]
Huh, I guess I assumed that exporting each function individually would solve this.
Does it work if you import only the necessary functions `import { func } from 'lib'` instead of `import * as ocl from 'lib'`

**Comment by pjeby** [comment]
The issue is that there's no ESM files in the distribution.  Switching the build from CommonJS to ESM should resolve it.

(Long version: dist/index.js uses everything it imports to set up an export object, so tree shaking isn't practical.  An ESM build of the module would have exports that would be understandable by rollup as being modular and tree-shakeable.)
